name: Judger

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'

    - name: Build with Maven
      run: mvn clean install

    - name: Rename artifact
      run: |
        COMMIT_ID=$(git rev-parse --short HEAD)
        VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
        JAR_PATH=$(find target -name "*.jar" | head -n 1)
        NEW_NAME="Judger-${COMMIT_ID}-${VERSION}.jar"
        echo "Renaming $JAR_PATH to $NEW_NAME"
        mv "$JAR_PATH" "target/$NEW_NAME"

    - name: Upload JAR artifact
      uses: actions/upload-artifact@v4
      with:
        name: judger-jar
        path: target/Judger-*.jar
