name: judger-build

on:
  push:
    branches:
      - master
    paths:
      - 'judger/**'
  pull_request:
    branches:
      - master
    paths:
      - 'judger/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'

    - name: Build with Maven
      working-directory: ./judger
      run: |
        mvn clean package -DskipTests

    - name: Rename and Prepare Artifacts
      working-directory: ./judger
      run: |
        echo "Contents of target/:"
        ls -lh target/

        COMMIT_ID=$(git rev-parse --short HEAD)
        VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)

        echo "Searching for jar-with-dependencies.jar..."
        JAR_DEP_PATH=$(find target -maxdepth 1 -name "*-jar-with-dependencies.jar" | head -n 1)
        echo "Searching for normal jar..."
        JAR_PATH=$(find target -maxdepth 1 -name "*.jar" ! -name "*-jar-with-dependencies.jar" | head -n 1)

        if [ -z "$JAR_DEP_PATH" ]; then
          echo "::error::No jar-with-dependencies.jar found in target/. Build may have failed."
          exit 1
        fi

        if [ -z "$JAR_PATH" ]; then
          echo "::error::No normal jar found in target/. Build may have failed."
          exit 1
        fi

        NEW_NAME_DEP="judger-${COMMIT_ID}-${VERSION}-with-dependencies.jar"
        echo "Renaming $JAR_DEP_PATH to $NEW_NAME_DEP"
        mv "$JAR_DEP_PATH" "target/$NEW_NAME_DEP"

        NEW_NAME="judger-${COMMIT_ID}-${VERSION}.jar"
        echo "Renaming $JAR_PATH to $NEW_NAME"
        mv "$JAR_PATH" "target/$NEW_NAME"

        echo "judger_jar_path=judger/target/$NEW_NAME" >> $GITHUB_ENV
        echo "judger_jar_dep_path=judger/target/$NEW_NAME_DEP" >> $GITHUB_ENV

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: judger-jars
        path: |
          ${{ env.judger_jar_path }}
          ${{ env.judger_jar_dep_path }}
