name: judger-test

on:
  push:
    branches:
      - master
    paths:
      - 'judger/**'
  pull_request:
    branches:
      - master
    paths:
      - 'judger/**'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Run tests with Maven
        working-directory: ./judger
        run: |
          mvn clean test
